--Ficha Socioeconómica
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 1', 'genograma1', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 2', 'genograma2', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 3', 'genograma3', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 4', 'genograma4', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 5', 'genograma5', 1);