--Ficha Socioeconómica
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 1', 'genograma1', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 2', 'genograma2', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 3', 'genograma3', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 4', 'genograma4', 1);
INSERT INTO FICHA_SOCIOECONOMICA (DINAMICA_FAMILIAR, GENOGRAMA, ID_EMPLEADO) VALUES ('dinamica familiar 5', 'genograma5', 1);


INSERT INTO INGRESO_ECONOMICO (ID, INGRESO_INDIVIDUAL, INGRESO_CONYUGE, INGRESO_PADRES,
INGRESO_JUBILACION, INGRESO_BONO_ESTADO, INGRESO_PENSION_JUDICIAL, INGRESO_OTROS,ID_FICHA_SOCIOECONOMICA) VALUES (1,23,23,44,33,22,11,30,1);